name: Generate changelog

on:
  push:
    tags:
      - 0.*[0-9].*[0-9]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install --upgrade pip
          pip install poetry
          poetry install
      - run: |
          poetry run towncrier build --yes --version=${{ github.ref_name }}
          user=$(gh api /user)
          user_name=$(jq -r '.login' <<<"$user")
          user_email=$(jq -r ".email | \"$user_name@users.noreply.github.com\"" <<<"$user")
          git config user.name "$user_name"
          git config user.email "$user_email"
          git commit -m "Gen changelog"
          git push origin HEAD:master
        env:
          GH_TOKEN: ${{ secrets.PAT }}