name: publish package
on:
  push:
    tags:
    - '**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code
    - uses: actions/setup-python@v4
      name: Set up Python
      with:
        python-version: '3.11'
    - name: Install tools
      run: |
        pip install --upgrade pip
        pip install poetry
    - name: Publish distribution 📦 to PyPI
      run: |
        poetry version ${{ github.ref_name }}
        poetry publish --build -u __token__ -p pypi-${{ secrets.PYPI_TOKEN }}
