name: publish package

on:
  push:
    tags:
      - 0.*[0-9].*[0-9]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip # not sure if it works
    - name: Install Poetry
      run: |
        pip install --upgrade pip
        pip install poetry
    - name: Set Poetry environment
      run: |
        poetry env use 3.11
    - name: Publish distribution 📦 to PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry version ${{ github.ref_name }}
        poetry publish --build
